sudo: required
language: python

services:
  - docker

matrix:
  include:
  - python:
    env:
      - NAME="NGINX Container"
      - RUN_IMAGE_NAME=nginx-modsecurity
      - IMAGE_NAME=vdveldet/nginx-modsecurity
      - IMAGE_COMPILE=nginx-compile
      - DOCKERFILE_COMPILE=Dockerfile_compile
      - DOCKERFILE=Dockerfile
      - VERSION=0.2
      - NGINX_VERSION=1.17.3
      - NGINX_FULL_VERSION=1.17.3-1+ubuntu18.04.1+deb.sury.org+1
      - MODSECURITY=3.0
      - MODSECURITY_RELEASE=3


install: true

script: pytest || true ? # This is needed for the build to complete

before_install:
  # First a Compile docker that will deliver the .deb an .so file
  - docker build --file $DOCKERFILE_COMPILE -t $IMAGE_COMPILE --build-arg VERSION --build-arg NGINX_VERSION --build-arg NGINX_FULL_VERSION --build-arg MODSECURITY --build-arg MODSECURITY_RELEASE .
  - docker run -d -p 127.0.0.1:80:80 --name $RUN_IMAGE_NAME compile      # Test is build is running
  - docker ps -a
  - curl http://127.0.0.1/nginx_status                                          # This URL is configured in the docker
  - docker logs compile
  - mkdir deb
  - docker cp $RUN_IMAGE_NAME:/ModSecurity/modsecurity_${MODSECURITY}-${MODSECURITY_RELEASE}_amd64.deb deb/
  - docker cp $RUN_IMAGE_NAME:/usr/share/nginx/modules/ngx_http_modsecurity_module.so deb/
  - ls -l deb/
  # From here the production docker is build
  - docker build --file $DOCKERFILE -t $IMAGE_NAME --build-arg VERSION --build-arg NGINX_VERSION --build-arg NGINX_FULL_VERSION --build-arg MODSECURITY --build-arg MODSECURITY_RELEASE .
  - docker run -d -p 127.0.0.1:80:80 --name $RUN_IMAGE_NAME $IMAGE_NAME      # Test is build is running
  - docker ps -a
  - curl http://127.0.0.1/nginx_status                                       # This URL is configured in the docker
  - curl http://127.0.0.1/test&id=1234 || true
  - docker logs $RUN_IMAGE_NAME
  - echo "$DOCKERHUB_PASSWD" | docker login --username "$DOCKERHUB_USERNAME" --password-stdin docker.io
  - docker tag "$IMAGE_NAME" "docker.io/${IMAGE_NAME}:latest"
  - docker tag "$IMAGE_NAME" "docker.io/${IMAGE_NAME}:${VERSION}"

deploy:
  - provider: script
    script: docker push "docker.io/${IMAGE_NAME}:latest"
    on:
      branch: master
  - provider: script
    script: docker push "docker.io/${IMAGE_NAME}:${VERSION}"
    on:
      branch: master

after_script:
  - docker pull "docker.io/${IMAGE_NAME}:latest"
